name: GameDispenser
version: "${project.version}"
main: net.galaxygaming.dispenser.GameDispenser
authors: [t7seven7t, Lactem]
softdepend: [RemoteEntities]
commands:
  gd:
    description: base command for GameDispenser
    aliases: [gamedispenser, game]